# Generated by Django 3.1.1 on 2020-09-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Mobile', models.IntegerField(default='0')),
                ('Message', models.CharField(default='', max_length=7000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Mobile', models.IntegerField(default='0')),
                ('Alternative_Mobile', models.IntegerField(default='0')),
                ('Address', models.CharField(default='', max_length=7000)),
                ('landmark', models.CharField(default='', max_length=150)),
                ('City', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=30)),
                ('Zip', models.CharField(default='', max_length=10)),
                ('Orders', models.CharField(default='', max_length=1000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=50)),
                ('product_Description', models.CharField(max_length=300)),
                ('categoty', models.CharField(default='', max_length=20)),
                ('sub_categoty', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default='0')),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
                ('product_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackOrder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('Order_id', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=70)),
                ('order_Description', models.CharField(default='', max_length=150)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Mobile', models.IntegerField(default='0')),
                ('Password', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
