# Generated by Django 3.1.1 on 2020-09-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_Description',
            field=models.CharField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_Name',
            field=models.CharField(max_length=120),
        ),
    ]
