# Generated by Django 3.1.1 on 2020-09-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200915_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Track_Id',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
